// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CheckInventoryServiceClient is the client API for CheckInventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckInventoryServiceClient interface {
	Check(ctx context.Context, in *CheckInventory, opts ...grpc.CallOption) (*CheckInventoryResponse, error)
}

type checkInventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckInventoryServiceClient(cc grpc.ClientConnInterface) CheckInventoryServiceClient {
	return &checkInventoryServiceClient{cc}
}

func (c *checkInventoryServiceClient) Check(ctx context.Context, in *CheckInventory, opts ...grpc.CallOption) (*CheckInventoryResponse, error) {
	out := new(CheckInventoryResponse)
	err := c.cc.Invoke(ctx, "/CheckInventoryService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckInventoryServiceServer is the server API for CheckInventoryService service.
// All implementations must embed UnimplementedCheckInventoryServiceServer
// for forward compatibility
type CheckInventoryServiceServer interface {
	Check(context.Context, *CheckInventory) (*CheckInventoryResponse, error)
	mustEmbedUnimplementedCheckInventoryServiceServer()
}

// UnimplementedCheckInventoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCheckInventoryServiceServer struct {
}

func (UnimplementedCheckInventoryServiceServer) Check(context.Context, *CheckInventory) (*CheckInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedCheckInventoryServiceServer) mustEmbedUnimplementedCheckInventoryServiceServer() {}

// UnsafeCheckInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckInventoryServiceServer will
// result in compilation errors.
type UnsafeCheckInventoryServiceServer interface {
	mustEmbedUnimplementedCheckInventoryServiceServer()
}

func RegisterCheckInventoryServiceServer(s grpc.ServiceRegistrar, srv CheckInventoryServiceServer) {
	s.RegisterService(&CheckInventoryService_ServiceDesc, srv)
}

func _CheckInventoryService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInventory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckInventoryServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CheckInventoryService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckInventoryServiceServer).Check(ctx, req.(*CheckInventory))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckInventoryService_ServiceDesc is the grpc.ServiceDesc for CheckInventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckInventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CheckInventoryService",
	HandlerType: (*CheckInventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _CheckInventoryService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inventory.proto",
}
